/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.estoque.view;

import com.mycompany.estoque.model.Log;
import com.mycompany.estoque.model.Produto;
import com.mycompany.estoque.model.Usuario;
import com.mycompany.estoque.repository.Conexao;
import com.mycompany.estoque.repository.ConexaoMySQL;
import com.mycompany.estoque.repository.UsuarioRepository;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class EdicaoUsuario extends javax.swing.JFrame {
    
    private UsuarioRepository usuarioRepository = new UsuarioRepository();
    private Connection connection;
    private Usuario usuarioLogado;

    /**
     * Creates new form CadastroUsuario
     */
    public EdicaoUsuario(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null);
        configurarConexao();
        this.usuarioLogado = usuario;
    }
    
    public EdicaoUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        configurarConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLocalizarIDUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboCargo = new javax.swing.JComboBox<>();
        FecharTela = new javax.swing.JButton();
        salvarEdicao = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        buscarID = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Digite o ID do Usuário:");

        jLabel2.setText("Nome :");

        jLabel3.setText("Usuário:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Cargo:");

        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Colaborador" }));
        comboCargo.setToolTipText("");

        FecharTela.setText("Fechar");
        FecharTela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FecharTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharTela(evt);
            }
        });

        salvarEdicao.setBackground(new java.awt.Color(0, 255, 0));
        salvarEdicao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salvarEdicao.setText("Salvar");
        salvarEdicao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salvarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarEdicaoActionPerformed(evt);
            }
        });

        excluirButton.setBackground(new java.awt.Color(255, 0, 0));
        excluirButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        excluirButton.setForeground(new java.awt.Color(255, 255, 255));
        excluirButton.setText("Excluir");
        excluirButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        buscarID.setText("Buscar");
        buscarID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIDBuscarID(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FecharTela)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocalizarIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(excluirButton)
                            .addComponent(salvarEdicao))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLocalizarIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarID))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(salvarEdicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirButton)
                .addGap(18, 18, 18)
                .addComponent(FecharTela)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FecharTela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharTela
        InicioUsuario usuario = new InicioUsuario(usuarioLogado);
        usuario.setVisible(true);//fecha a tela de cadastro e inicia a tela inicial novamente
        dispose();
    }//GEN-LAST:event_FecharTela

    private void configurarConexao(){
        
        // Configurando a conexão com os dados do banco local
        Conexao conexao = new Conexao(
                "localhost",
                "root",
                "Guirp007007!", //configure sua conexão com o banco de dados
                3306,
                "estoque"
        );

        ConexaoMySQL conexaoMySQL = new ConexaoMySQL(conexao);  //iniciando a com os dados do objeto conexao
        if (conexaoMySQL.conectar()) { 
            connection = ConexaoMySQL.connection;   //faz a conexão
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);   //mmensagem de erro
            return; 
        }
    }
    
    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed

        try {
            int id = Integer.parseInt(txtLocalizarIDUsuario.getText()); //pega o id colocado pelo usuário

            // Etapa 1: Confirmação de exclusão
            int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza de que deseja excluir o usuário com ID " + id + "?",
                "Confirmação de Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );

            if (confirmacao == JOptionPane.YES_OPTION) {
                // Etapa 2: Tentativa de exclusão
                boolean sucesso = usuarioRepository.deletar(connection, id);

                if (sucesso) {
                    // Etapa 3: Mensagem de sucesso
                    JOptionPane.showMessageDialog(
                        this,
                        "Usuário com ID " + id + " foi excluído com sucesso!",
                        "Exclusão Bem-Sucedida",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                    limparCampos(); // Limpa os campos após exclusão
                    Log log = new Log();
                    log.setLogscol("Usuário excluiu o usuario com id " + id + " no sistema");
                    log.setIdusuario(usuarioLogado.getId());
                    usuarioRepository.inserirLog(connection, log);
                } else {
                    // Etapa 4: Mensagem de falha
                    JOptionPane.showMessageDialog(
                        this,
                        "Usuário com ID " + id + " não foi encontrado ou não pôde ser excluído.",
                        "Erro na Exclusão",
                        JOptionPane.ERROR_MESSAGE
                    );
                }
            } else {
                // Caso o usuário cancele a exclusão
                JOptionPane.showMessageDialog(
                    this,
                    "A exclusão foi cancelada pelo usuário.",
                    "Operação Cancelada",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                this,
                "ID inválido. Por favor, insira um número válido.", //mensagem de erro
                "Erro de Entrada",
                JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao tentar excluir o produto: " + ex.getMessage(),  //mensagem de erro
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_excluirButtonActionPerformed

    private void limparCampos(){ //função para limpar os JLabels da página
        txtNomeUsuario.setText("");
        txtUsuario.setText("");
        txtSenha.setText("");
        
    }
    
    
    private void salvarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarEdicaoActionPerformed
        
        try {
            // Criar o objeto produto com os dados preenchidos
            Usuario usuario = new Usuario();
            usuario.setId(Integer.parseInt(txtLocalizarIDUsuario.getText()));
            usuario.setUsuario(txtUsuario.getText());
            usuario.setNome(txtNomeUsuario.getText());
            usuario.setSenha(txtSenha.getText());
            
            int cargo = comboCargo.getSelectedIndex();
            usuario.setCargo(cargo + 1);

            // Etapa 1: Confirmação de atualização
            int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza de que deseja atualizar o produto com ID " + usuario.getId() + "?",
                "Confirmação de Atualização",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );

            if (confirmacao == JOptionPane.YES_OPTION) {
                // Etapa 2: Atualizar o produto no banco de dados
                boolean sucesso = usuarioRepository.atualizar(connection, usuario);

                if (sucesso) {
                    // Etapa 3: Mensagem de sucesso
                    JOptionPane.showMessageDialog(
                        this,
                        "Produto com ID " + usuario.getId() + " atualizado com sucesso!",
                        "Atualização Bem-Sucedida",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                    Log log = new Log();
                    log.setLogscol("Usuário Editou um produto no sistema");
                    log.setIdusuario(usuarioLogado.getId());
                    
                    usuarioRepository.inserirLog(connection, log);
                } else {
                    // Etapa 4: Mensagem de falha
                    JOptionPane.showMessageDialog(
                        this,
                        "Não foi possível atualizar o produto com ID " + usuario.getId() + ".",
                        "Erro na Atualização",
                        JOptionPane.ERROR_MESSAGE
                    );
                }
            } else {
                // Caso o usuário cancele a atualização
                JOptionPane.showMessageDialog(
                    this,
                    "A atualização foi cancelada pelo usuário.",
                    "Operação Cancelada",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                this,
                "Erro nos dados inseridos. Por favor, verifique os valores preenchidos.",   //mmensagem de erro
                "Erro de Entrada",
                JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao tentar atualizar o produto: " + ex.getMessage(),   //mmensagem de erro
                "Erro",  
                JOptionPane.ERROR_MESSAGE
            );
        }
       
     
    }//GEN-LAST:event_salvarEdicaoActionPerformed

    private void buscarIDBuscarID(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIDBuscarID

        try{
            int id = Integer.parseInt(txtLocalizarIDUsuario.getText()); //pega o id colocado pelo usuário

            Usuario usuario = usuarioRepository.selecionar(connection, id);  //chama a função de selecionar os produtos, recebendo o id que o usuário colocou

            if (usuario != null) {
                // Preencher os campos com os dados do produto encontrado
                txtNomeUsuario.setText(usuario.getNome());
                txtUsuario.setText(usuario.getUsuario());
                txtSenha.setText(String.valueOf(usuario.getSenha()));
                int cargo = usuario.getCargo();
                comboCargo.setSelectedIndex(cargo - 1);
                
            } else {
                // Caso o produto não seja encontrado
                JOptionPane.showMessageDialog(this, "Usuario não encontrado!", "Erro", JOptionPane.WARNING_MESSAGE);
                limparCampos(); // Limpar os campos para evitar exibição de dados incorretos
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Erro ao buscar o Usuario: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_buscarIDBuscarID

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdicaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdicaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdicaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdicaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdicaoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FecharTela;
    private javax.swing.JButton buscarID;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JButton excluirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton salvarEdicao;
    private javax.swing.JTextField txtLocalizarIDUsuario;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
