/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.estoque.view;

import com.mycompany.estoque.model.Produto;
import com.mycompany.estoque.model.Usuario;
import com.mycompany.estoque.repository.Conexao;
import com.mycompany.estoque.repository.ConexaoMySQL;
import com.mycompany.estoque.repository.ProdutoRepository;
import com.mycompany.estoque.repository.UsuarioRepository;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilh
 */
public class RelatorioUsuarioRelacao extends javax.swing.JFrame {
    private UsuarioRepository usuarioRepository = new UsuarioRepository();
    private Connection connection;
    private Usuario usuarioLogado;
    /**
     * Creates new form RelatorioUsuarioRelacao
     */
    public RelatorioUsuarioRelacao(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null);
        configurarConexao();
        carregarTabelaTodos();
        this.usuarioLogado = usuario;
    }
    
    public RelatorioUsuarioRelacao() {
        initComponents();
        setLocationRelativeTo(null);
        configurarConexao();
        carregarTabelaTodos();
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        relatorioCompletoButton1 = new javax.swing.JButton();
        relatorioCompletoButton = new javax.swing.JButton();
        relatorioCompletoButton2 = new javax.swing.JButton();
        FecharTela = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        relatorioUsuario = new javax.swing.JTable();

        relatorioCompletoButton1.setText("Relatório Logs");
        relatorioCompletoButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        relatorioCompletoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioCompletoButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        relatorioCompletoButton.setText("Relatório Usuários");
        relatorioCompletoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        relatorioCompletoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioCompletoButtonActionPerformed(evt);
            }
        });

        relatorioCompletoButton2.setText("Relatório Logs");
        relatorioCompletoButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        relatorioCompletoButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioCompletoButton2ActionPerformed(evt);
            }
        });

        FecharTela.setText("Fechar");
        FecharTela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FecharTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharTela(evt);
            }
        });

        relatorioUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        relatorioUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Usuario", "Senha", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(relatorioUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(relatorioCompletoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(relatorioCompletoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FecharTela)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(relatorioCompletoButton)
                            .addComponent(relatorioCompletoButton2))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(FecharTela)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void relatorioCompletoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioCompletoButtonActionPerformed
        carregarTabelaTodos();
    }//GEN-LAST:event_relatorioCompletoButtonActionPerformed

    private void relatorioCompletoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioCompletoButton1ActionPerformed
        RelatorioUsuarioLogs relatorioUsuarioLogs = new RelatorioUsuarioLogs(usuarioLogado);
        relatorioUsuarioLogs.setVisible(true);
        dispose();
    }//GEN-LAST:event_relatorioCompletoButton1ActionPerformed

    private void relatorioCompletoButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioCompletoButton2ActionPerformed
        RelatorioUsuarioLogs relatorioUsuarioLogs = new RelatorioUsuarioLogs(usuarioLogado);
        relatorioUsuarioLogs.setVisible(true);
        dispose();
    }//GEN-LAST:event_relatorioCompletoButton2ActionPerformed

    private void FecharTela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharTela
        InicioUsuario inicioUsuario = new InicioUsuario(usuarioLogado);
        inicioUsuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_FecharTela
    private void configurarConexao(){
        // Configurando a conexão
        Conexao conexao = new Conexao(
                "localhost",
                "root",
                "Guirp007007!",  //configure sua conexão com o banco de dados
                3306,
                "estoque"
        );

        ConexaoMySQL conexaoMySQL = new ConexaoMySQL(conexao); //iniciando a com os dados do objeto conexao
        if (conexaoMySQL.conectar()) {  
            connection = ConexaoMySQL.connection;  //faz a conexão
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE); //mensagem de erro
            return;  
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioUsuarioRelacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioUsuarioRelacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioUsuarioRelacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioUsuarioRelacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioUsuarioRelacao().setVisible(true);

            }
        });
    }
    
    private void carregarTabelaTodos() { //função para buscar todos os produtos do banco e mostrar no JTable
        
              
        // Selecionando os produtos
        List<Usuario> usuarios = usuarioRepository.selecionarTodos(connection);

        if (usuarios == null || usuarios.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum produto encontrado.", "Aviso", JOptionPane.INFORMATION_MESSAGE); //mensagem avisando que não tem produtos cadastrados no banco
            return;
        }
        
            // Printando os dados da lista
            System.out.println("Lista de usuários encontrados:");
            for (Usuario usuario : usuarios) {
                System.out.println("ID: " + usuario.getId() +
                                   ", Nome: " + usuario.getNome() +
                                   ", Usuário: " + usuario.getUsuario() +
                                   ", Senha: " + usuario.getSenha() +
                                   ", Cargo: " + usuario.getCargo());
            }

        // Criando o modelo da tabela
        DefaultTableModel modeloTabela = (DefaultTableModel) relatorioUsuario.getModel();
        modeloTabela.setRowCount(0); // Limpa os dados anteriores da tabela

        for (Usuario usuario : usuarios) {

            modeloTabela.addRow(new Object[]{
                    usuario.getId(),
                    usuario.getNome(),    
                    usuario.getUsuario(),   //adiciona os dados na tabela
                    usuario.getSenha(),
                    usuario.getCargo()
            });
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FecharTela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton relatorioCompletoButton;
    private javax.swing.JButton relatorioCompletoButton1;
    private javax.swing.JButton relatorioCompletoButton2;
    private javax.swing.JTable relatorioUsuario;
    // End of variables declaration//GEN-END:variables
}
